[package]
name = "sagitario-lng"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/juanestban/sagitario-engine"
authors = ["Juan Esteban - juanestbandev"]

[dependencies]
sagitario-logger = { path = "../../core/logger" }

[lib]
path = "./src/lib.rs"
